### ISSUE TITLE
Solved: pushing on protected branches

### ISSUE THREAD

**Issue by simonecorsi** [jonwa/lerna-release-workflow#9]
Hey 👋 

Thanks for this example it helped me with one of my projects!

I had a problem pushing on protected branches so I'm leaving the solution here so maybe it can help someone else! If you want I can do a PR to the README, just let me know!

Lerna can't push on protected branches (eg: main) even if using a PAT of an owner with the correct permission following this approach, but it is easily fixed by turning off `persist-credentials` and setting the repo URL alongside the user:

```yml
# ...
            - uses: actions/checkout@v3
              with:
                  persist-credentials: false
                  fetch-depth: 0
# ...
          - name: Config git user
              run: |
                  git config --global user.name "${{ github.actor }}"
                  git config --global user.email "${{ github.actor }}@users.noreply.github.com"
                  git remote set-url origin https://${{ github.actor }}:${{ secrets.GH_NODE_TOKEN }}@github.com/${{ github.repository }}
# ...
```
